### ISSUE TITLE
Why can't I build a structured mesh?

### ISSUE THREAD

**Issue by Phqiii** [japaf/foamgen#18]
The shell shows the following:
```
Converting .geo to .stl
Moving STL to periodic box.
Creating structured mesh.
Optimizing porosity and strut content
Traceback (most recent call last):
  File "/home/phqiii/miniconda3/bin/foamgen", line 8, in <module>
    sys.exit(parse_cli_and_generate())
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/foamgen/generation.py", line 92, in parse_cli_and_generate
    generate(cfg)
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/foamgen/generation.py", line 156, in generate
    smesh.structured_mesh(cfg.filename,
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/foamgen/smesh.py", line 49, in structured_mesh
    res = root_scalar(por_fs_res,
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/scipy/optimize/_root_scalar.py", line 257, in root_scalar
    r, sol = methodc(f, x0, args=args, fprime=None, fprime2=None,
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/scipy/optimize/_zeros_py.py", line 333, in newton
    q0 = func(p0, *args)
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/foamgen/smesh.py", line 112, in por_fs_res
    voxelize_morphology(fname, delta)
  File "/home/phqiii/miniconda3/lib/python3.9/site-packages/foamgen/smesh.py", line 178, in voxelize_morphology
    call = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/home/phqiii/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/phqiii/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'binvox'
```

**Comment by japaf** [comment]
Looks like a problem with binvox. It should be installed in /usr/local/bin/. Also check if you have permission to execute it.

**Comment by Phqiii** [comment]
Thank you for your reply. However, can I take the liberty of asking how you optimized the unstructured mesh in this percedure? I find that even the meshes of the models generated by the basic configuration file are somewhat cluttered. There may be intersections and overlaps of meshes, resulting in mesh shapes such as elongated triangles and irregular polygons. As a novice, I am very confused about dealing with these meshes.
like the following figure shows.
![screenshot2](https://user-images.githubusercontent.com/83255308/178241722-68d58c05-b83d-4d86-bb7d-f5d9ce86afef.png)

**Comment by japaf** [comment]
Is that the output of the tessellation? In my work, I mostly used tessellation to determine where the cells and walls are and then create a structured grid on top of that. Later on, I tried to make some structured tetrahedral volumetric meshes as well, but I did not get as far as I wanted before I went to other projects. I never used surface meshes to simulate anything so their quality did not bother too much. If the image was created as I think it was, it's quite likely that the quality could be improved by tweaking the gmsh meshing procedure.
